name: haskell-serverless-test
version: 0.1.0
license: BSD3
author: "my name"
maintainer: "example@example.com"
copyright: "2019 Author name here"

extra-source-files:
  - README.md
  - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/githubuser/mypackage#readme>

dependencies:
  - base >= 4.7 && < 5
  - serverless-haskell
  - aeson
  - http-conduit
  - bytestring
  - utf8-string
  - text
  - pretty-show
  - lens
  - amazonka-core
  - amazonka-dynamodb
  - amazonka
  - amazonka-s3
  - dotenv
  - filepath
  - directory
  - containers
  - unordered-containers
  - pretty-simple

library:
  source-dirs: src

executables:
  get-user-exe:
    main: Main.hs
    source-dirs: app/get-user
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - haskell-serverless-test

  # create-user-exe:
  #   main: Main.hs
  #   source-dirs: app/create-user
  #   ghc-options:
  #     - -threaded
  #     - -rtsopts
  #     - -with-rtsopts=-N
  #   dependencies:
  #     - haskell-serverless-test

  update-user-exe:
    main: Main.hs
    source-dirs: app/update-user
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - haskell-serverless-test

  get-users-exe:
    main: Main.hs
    source-dirs: app/get-users
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - haskell-serverless-test
  # s3-test-exe:
  #   main: Main.hs
  #   source-dirs: app/s3-test
  #   ghc-options:
  #     - -threaded
  #     - -rtsopts
  #     - -with-rtsopts=-N
  #   dependencies:
  #     - haskell-serverless-test
  # dynamo-test-exe:
  #   main: Main.hs
  #   source-dirs: app/dynamo-test
  #   ghc-options:
  #     - -threaded
  #     - -rtsopts
  #     - -with-rtsopts=-N
  #   dependencies:
  #     - haskell-serverless-test
