Resources:
  mainTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: haskell-users
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S

      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE

      GlobalSecondaryIndexes:
        - IndexName: all_users
          KeySchema:
            - AttributeName: SK
              KeyType: HASH
          Projection:
            ProjectionType: ALL

      BillingMode: PAY_PER_REQUEST
